baseURL = "https://takeupsomething.com/"
languageCode = "en-us"
title = "Takeup - Must-have items for anybody to take up anything"
theme = "ts"
googleAnalytics = "G-4KZWM8KHSB"
[related]
  toLower = false

  [[related.indices]]
      name = "categories"
          weight = 100
[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 2
    ordered = true
