baseURL = "https://takeupsomething.com/"
languageCode = "en-us"
title = "Takeup - Must-have items for anybody to take up anything"
theme = "ts"
[related]
  toLower = false

  [[related.indices]]
      name = "categories"
          weight = 100
