baseURL = "https://takeupsomething.com/"
description = ""
languageCode = "en-us"
title = "Getting started guides in anything | Takeup"
theme = "ts"
googleAnalytics = "G-4KZWM8KHSB"
[related]
  toLower = false

  [[related.indices]]
      name = "categories"
          weight = 100
[markup]
  [markup.tableOfContents]
    ordered = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputFormats.SearchIndex]
  baseName = "search"
  mediaType = "application/json"

[outputs]
  home = [ "HTML", "RSS", "SearchIndex" ]

[params]
  tagline = "Getting started guides in anything"
